# Generated by Django 3.2 on 1979-12-31 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.IntegerField(null=True)),
                ('course', models.ManyToManyField(to='skool.Courses')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('teacher_id', models.CharField(max_length=200, null=True)),
                ('teacher_email', models.EmailField(blank=True, max_length=200, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('student_id', models.CharField(max_length=200, null=True, unique=True)),
                ('student_bday', models.DateField(blank=True, null=True)),
                ('student_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skool.level')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=200, null=True)),
                ('review', models.CharField(choices=[('excellent', 'excellent'), ('Good', 'Good'), ('Satisfactory', 'Satisfactory'), ('Poor', 'Poor'), ('Fail', 'Fail')], max_length=200, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skool.courses')),
                ('current_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skool.level')),
                ('studentprofile', models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skool.studentprofile')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.CreateModel(
            name='NewsFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('category', models.CharField(blank=True, choices=[('News', 'News'), ('Tech', 'Tech'), ('Business', 'Business'), ('Lifestyle', 'Lifestyle'), ('Feature', 'Feature')], max_length=200, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(to='skool.Tag')),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.AddField(
            model_name='level',
            name='teacher',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skool.teacherprofile'),
        ),
        migrations.AddField(
            model_name='courses',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skool.teacherprofile'),
        ),
    ]
