# Generated by Django 3.2 on 1980-01-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='teacher_email',
            new_name='teacheremail',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='teacher_id',
            new_name='teacherid',
        ),
    ]
