# Generated by Django 3.2 on 1980-01-01 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0002_auto_19800101_0151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='teacheremail',
            new_name='teacher_email',
        ),
        migrations.RenameField(
            model_name='teacherprofile',
            old_name='teacherid',
            new_name='teacher_id',
        ),
    ]
