# Generated by Django 3.2 on 1979-12-31 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0003_auto_19800101_0158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='course',
        ),
        migrations.AddField(
            model_name='courses',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='skool.level'),
        ),
    ]
