# Generated by Django 3.2 on 1980-01-01 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0004_auto_19800101_0037'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
