# Generated by Django 3.2 on 1980-01-01 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0005_studentprofile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
