# Generated by Django 3.2 on 1980-01-01 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0006_teacherprofile_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course_name',
            new_name='name',
        ),
    ]
