# Generated by Django 3.2 on 1980-01-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0007_rename_course_name_courses_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
