# Generated by Django 3.2 on 1979-12-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0009_auto_19800101_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='slug',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(to='skool.Courses'),
        ),
    ]
