# Generated by Django 3.2 on 1979-12-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0011_auto_19800101_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='teacher',
            field=models.ManyToManyField(to='skool.TeacherProfile'),
        ),
    ]
