# Generated by Django 3.2 on 1980-01-01 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0012_studentprofile_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='skool.courses'),
        ),
    ]
