# Generated by Django 3.2 on 1979-12-31 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0013_auto_19800101_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='teacher',
        ),
    ]
