# Generated by Django 3.2 on 1979-12-31 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0014_remove_studentprofile_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='course',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(to='skool.Courses'),
        ),
    ]
