# Generated by Django 3.2 on 1980-01-01 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0015_auto_19800101_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ManyToManyField(related_name='subject', to='skool.Courses'),
        ),
    ]
