# Generated by Django 3.2 on 1980-01-01 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0016_alter_studentprofile_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='level',
        ),
    ]
