# Generated by Django 3.2 on 1979-12-31 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0018_auto_19800101_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
