# Generated by Django 3.2 on 1979-12-31 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0021_alter_studentprofile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
