# Generated by Django 3.2 on 1980-01-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0022_alter_studentprofile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
