# Generated by Django 3.2 on 2021-09-01 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0026_auto_20210901_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
