# Generated by Django 3.2 on 2021-09-01 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0028_cart_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='status',
        ),
    ]
