# Generated by Django 3.2 on 2021-09-01 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0029_remove_product_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='carts',
        ),
        migrations.RemoveField(
            model_name='order',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
