# Generated by Django 3.2 on 1980-01-01 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0030_auto_20210901_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=4000, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
