# Generated by Django 3.2 on 1979-12-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0031_messages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='teacherprofile',
            name='slug',
        ),
    ]
