# Generated by Django 3.2 on 1980-01-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skool', '0034_result_term'),
    ]

    operations = [
        migrations.AddField(
            model_name='result',
            name='exam',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='first_test',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='second_test',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
